### PR TITLE
update resteasy to `6.1.0.Final`

### PR DESCRIPTION
**Pull request by liweinan**

### CODE REVIEW

**Comment by liweinan** [comment]
@jamezp The problem in build process looks like a bug in RESTEasy 6.1.0.Beta3:

https://github.com/resteasy/resteasy-spring/runs/7636386855?check_suite_focus=true#step:4:4853

Could you please help to check it? Thanks!

**Comment by jamezp** [comment]
@liweinan You also need to upgrade WildFly to 27.0.0.Alpha3. That is where that module lives.

**Comment by liweinan** [comment]
@jamezp okay!

**Comment by jamezp** [comment]
@liweinan We may has well upgrade to RESTEasy 6.1.0.Final now. As for the new failure, that looks like a retest should fix that. I ran this locally and it passed.

**Comment by liweinan** [comment]
@jamezp okay!

**Comment by liweinan** [comment]
@jamezp It seems I can't reproduce this problem on my local machine:

image

Could you please help to check it? Thanks!

**Comment by jamezp** [comment]
@liweinan I know what it is. OpenSAML is not in Maven Central so we probably need to add the repository. I'm surprised I haven't see this on RESTEasy so I'm testing it now there. Let me think of a good way to do this.

**Comment by liweinan** [comment]
@jamezp thanks!

**Comment by jamezp** [comment]
@liweinan Ah, RESTEasy works because I added the repository :) You'll want to add this to your repositories in `testsuite/pom.xml`.
```xml
<!-- Remove below repo after opensaml 4.2.0 is accessible from maven central repo-->
<repository>
    <id>opensaml-repo</id>
    <name>opensaml</name>
    <url>https://build.shibboleth.net/nexus/content/groups/public</url>
    <releases>
        <enabled>true</enabled>
    </releases>
</repository>
```

**Comment by jamezp** [comment]
FWIW this was my commit https://github.com/resteasy/resteasy/pull/3146/commits/9d7a92f0c346f9e58071768fbf458b3558bb3454

**Comment by liweinan** [comment]
@jamezp okay!

**Comment by jamezp** [comment]
I'd also suggest, once complete, squashing the commits. Not required though. I do see some failures locally that I have not looked into yet.

**Review by jamezp — APPROVED** [review]
The changes look good to me. I would suggest squashing the commits before merging, but that is up to you :)

**Comment by liweinan** [comment]
@jamezp Yes sir!

**Pull request merged**
